services:
  comment-service:
    build: .
    container_name: comment-service
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo-api
    networks:
      - microservices-network
  mongo:
    image: mongo
    container_name: mongo3
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27018"
    networks:
      - microservices-network
networks:
  microservices-network:
    external: true

volumes:
  mongodb_data:
