

services:
  comment-service:
    build: .
    container_name: comment-service
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/comment-service
    depends_on:
      - mongo
    networks:
      - microservices-network

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  mongodb_data:
