services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - microservices-network
    environment:
      - NODE_ENV=development

networks:
  microservices-network:
    external: true
