services:
  # Service pour le microservice Likes
  like-service:
    build: ./like-service  # Spécifie le dossier pour construire l'image
    container_name: like-service
    restart: unless-stopped
    ports:
      - "4002:4002"  # Expose le port 4002 pour le microservice Likes
    environment:
      - MONGO_URI=mongodb://mongo:27019/like-service  
    depends_on:
      - mongo3  
    networks:
      - backend

  # Service MongoDB
  mongo3:
    image: mongo
    container_name: mongo3
    restart: unless-stopped
    volumes:
      - mongo3_data:/data/db
    ports:
      - "27019:27017"  
    networks:
      - backend

volumes:
  mongo3_data:

networks:
  backend:
    driver: bridge