version: "3.8"

services:
  posts:
    build: ./Posts
    container_name: posts
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./Posts:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo-api
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
