services:
  comment-service:
    build: ./comment-service
    container_name: comment-service
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/social-app
    depends_on:
      - mongo
      - post-service
    networks:
      - backend

  post-service:
    build: ./post-service
    container_name: post-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/social-app
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge