services:
  followers:
    build: .
    container_name: followers
    restart: unless-stopped
    depends_on:
      - mongofollowers
    volumes:
      - .:/app
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongofollowers:27017/followers-api
    networks:
      - microservices-network
  mongofollowers:
    image: mongo
    container_name: mongofollowers
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27020:27017"
    networks:
      - microservices-network
networks:
  microservices-network:
    external: true

volumes:
  mongodb_data:
