services:
  like-service:
    build: .
    container_name: like-service
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongo-like:27017/like-service
    depends_on:
      - mongo-like
    networks:
      - microservices-network

  mongo-like:
    image: mongo
    container_name: mongo-like
    restart: unless-stopped
    volumes:
      - mongo-like_data:/data/db
    ports:
      - "27019:27017"
    networks:
      - microservices-network

volumes:
  mongo-like_data:

networks:
  microservices-network:
    driver: bridge