services:
  like-service:
    build: .
    container_name: like-service
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo-api
    networks:
      - microservices-network
  mongo:
    image: mongo
    container_name: mongo2
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27019:27019"
    networks:
      - microservices-network
networks:
  microservices-network:
    external: true

volumes:
  mongodb_data:
