services:
  posts:
    build: .
    container_name: posts
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo-api
    networks:
      - microservices-network
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-network
networks:
  microservices-network:
    external: true

volumes:
  mongodb_data:
