version: '3.8'

services:
  posts:
    build: .
    container_name: posts
    restart: unless-stopped
    depends_on:
      - mongo-profil-page
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo-profil-page:27018/todo-api  
    networks:
      - microservices-network

  mongo-profil-page:  
    image: mongo
    container_name: mongo-profil-page
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  mongodb_data:
